In [1]:
import pandas as pd

In [2]:
def time_converter(year,idx,total_timestep=35040):
    """
    Input
    -------------------
    year: int, year to be converted
    idx: int, index of timestep in the specific year, SHOULD start from zero
    total_timestep: total timestep of the specific year
    
    Output
    -------------------
    pandas Timestamp of the time corresponding to the idx
    """
    index = pd.date_range(start='1/1/{0}'.format(year), end='1/1/{0}'.format(year+1), periods=total_timestep+1)
    time = index[idx]
    return time

In [3]:
def price_generator(year,total_timestep=35040):
    index = pd.date_range(start='1/1/{0}'.format(year), end='1/1/{0}'.format(year+1), periods=total_timestep+1)
    e_price_df = pd.DataFrame(index, columns=['date_time'])
    e_price_df['e_price'] = 0
    for idx in range(total_timestep):
        time = index[idx]
        if 0 <= time.hour < 14:
            e_price = 8
        elif 14 <= time.hour < 16 or 21 <= time.hour < 23:
            e_price = 16
        elif 16 <= time.hour < 21:
            e_price = 25
        else :
            e_price = 8
        e_price_df.loc[idx,'e_price'] = e_price
        
    return e_price_df
            
    

In [4]:
e_price_df_2015 = price_generator(2015,total_timestep=35040)
e_price_df_2015.to_csv('e_price_2015.csv', index=False)

KeyboardInterrupt: 

In [20]:
e_price_df_2013 = price_generator(2013,total_timestep=35040)
e_price_df_2013.to_csv('e_price_2013.csv', index=False)

In [21]:
e_price_df_2014 = price_generator(2014,total_timestep=35040)
e_price_df_2014.to_csv('e_price_2014.csv', index=False)

In [22]:
e_price_df_2017 = price_generator(2017,total_timestep=35040)
e_price_df_2017.to_csv('e_price_2017.csv', index=False)

In [24]:
max(5,10)

10

In [4]:
e_price_df_2018 = price_generator(2018,total_timestep=35040)
e_price_df_2018.to_csv('e_price_2018.csv', index=False)

In [2]:
ed2017 = pd.read_csv("e_d_price_2017.csv", index_col=0, parse_dates=True)
ed2017.head()

e_price  d_price
date_time                            
2017-01-01 00:00:00   0.1115    21.08
2017-01-01 00:15:00   0.1115    21.08
2017-01-01 00:30:00   0.1115    21.08
2017-01-01 00:45:00   0.1115    21.08
2017-01-01 01:00:00   0.1115    21.08

In [5]:
ed2017_hourly =ed2017.resample('60T').mean()

In [7]:
ed2017_hourly.shape


(8761, 2)

In [8]:
24*365

8760

In [9]:
4*4


16

In [ ]:
data$tow <- data$hour + lubridate::minute(data$dts)/60 + data$wday*24

In [25]:
# index_1 = pd.to_datetime(ed2017.index)
ed2017.index[20]

Timestamp('2017-01-01 05:00:00')

In [31]:
toto =ed2017.index[21]
toto

Timestamp('2017-01-01 05:15:00')

In [32]:
toto.hour

5

In [33]:
toto.minute

15

In [51]:
toto.weekday()

6

In [47]:
titi = ed2017.index.hour + ed2017.index.minute/60.0 + ed2017.index.weekday* 24
titi[95:195]

Float64Index([167.75,    0.0,   0.25,    0.5,   0.75,    1.0,   1.25,    1.5,
                1.75,    2.0,   2.25,    2.5,   2.75,    3.0,   3.25,    3.5,
                3.75,    4.0,   4.25,    4.5,   4.75,    5.0,   5.25,    5.5,
                5.75,    6.0,   6.25,    6.5,   6.75,    7.0,   7.25,    7.5,
                7.75,    8.0,   8.25,    8.5,   8.75,    9.0,   9.25,    9.5,
                9.75,   10.0,  10.25,   10.5,  10.75,   11.0,  11.25,   11.5,
               11.75,   12.0,  12.25,   12.5,  12.75,   13.0,  13.25,   13.5,
               13.75,   14.0,  14.25,   14.5,  14.75,   15.0,  15.25,   15.5,
               15.75,   16.0,  16.25,   16.5,  16.75,   17.0,  17.25,   17.5,
               17.75,   18.0,  18.25,   18.5,  18.75,   19.0,  19.25,   19.5,
               19.75,   20.0,  20.25,   20.5,  20.75,   21.0,  21.25,   21.5,
               21.75,   22.0,  22.25,   22.5,  22.75,   23.0,  23.25,   23.5,
               23.75,   24.0,  24.25,   24.5],
             dtyp

In [48]:
167.75/.25


671.0

In [49]:
24*4*7

672

In [ ]:
minuteOfWeek = 24*60*timeVec$wday+60*timeVec$hour + timeVec$min
intervalOfWeek = 1+floor(minuteOfWeek/intervalMinutes)

In [ ]:
titi = 60 * ed2017.index.hour + ed2017.index.minute + toto.weekday() * 24 * 60

In [59]:
dts = pd.date_range(start='1/1/{0}'.format(2017), end='1/1/{0}'.format(2017+1), periods=35040+1)

In [57]:
tow = 60 * ed2017.index.hour + ed2017.index.minute + toto.weekday() * 24 * 60
tow

35040.0

In [ ]:
60*

In [3]:
ed2017 = pd.read_csv("e_d_price_2017.csv", index_col=0, parse_dates=True)
ed2017.head()

e_price  d_price
date_time                            
2017-01-01 00:00:00   0.1115    21.08
2017-01-01 00:15:00   0.1115    21.08
2017-01-01 00:30:00   0.1115    21.08
2017-01-01 00:45:00   0.1115    21.08
2017-01-01 01:00:00   0.1115    21.08

In [4]:
i = 0
#ed2017.loc[i:(i+96),'e_price'] 
# ed2017.loc[0:96,'e_price'] 

time_interval = pd.date_range(
            start="1/1/{0}".format(2017),
            end="1/1/{0}".format(2017 + 1),
            periods=35040 + 1)


In [5]:
35040-96

34944

In [8]:
i =35040+2-96 -96
j = i+(24*4-1)
time_interval[i] 


Timestamp('2017-12-30 00:30:00')

In [30]:
time_interval[j]

Timestamp('2017-12-31 00:15:00')

In [24]:
(35040 - 95 - 1)

34944

In [18]:
idx = ed2017.loc[time_interval[i]:time_interval[j]].index
len(idx)

97

In [24]:
df =ed2017.loc[idx,'e_price']

In [26]:
df.groupby([idx.hour]).mean()

date_time
0     0.1115
1     0.1115
2     0.1115
3     0.1115
4     0.1115
5     0.1115
6     0.1115
7     0.1115
8     0.1115
9     0.1115
10    0.1115
11    0.1115
12    0.1115
13    0.1115
14    0.1115
15    0.1115
16    0.1438
17    0.1438
18    0.1438
19    0.1438
20    0.1438
21    0.1115
22    0.1115
23    0.1115
Name: e_price, dtype: float64

In [27]:
i = 0
j = i+95
idx = ed2017.loc[time_interval[i]:time_interval[j]].index
df =ed2017.loc[idx,'e_price']
df.groupby([idx.hour]).mean()

date_time
0     0.1115
1     0.1115
2     0.1115
3     0.1115
4     0.1115
5     0.1115
6     0.1115
7     0.1115
8     0.1115
9     0.1115
10    0.1115
11    0.1115
12    0.1115
13    0.1115
14    0.1115
15    0.1115
16    0.1438
17    0.1438
18    0.1438
19    0.1438
20    0.1438
21    0.1115
22    0.1115
23    0.1115
Name: e_price, dtype: float64

In [7]:

def get_data_from_df(df, start_time=None, end_time=None):
    """Get a DataFrame of all price variables from csv files
        Parameters
        ----------
        start_time : datetime
            Start time of timeseries
        end_time : datetime
            End time of timeseries
        -------
        df: pandas DataFrame
            DataFrame where each column is a variable in the variables section in the configuration
    """
    df.index = pd.to_datetime(df.index)
    idx = df.loc[start_time:end_time].index
    df = df.loc[idx,]

    return df

In [45]:
i = 103
j = i+ (4*3 -(1))
start = time_interval[i]
end = time_interval[j-i%4]
df_price = get_data_from_df(
            df=ed2017, 
            start_time=start, 
            end_time=end)
df_price.groupby([df_price.index.hour])['e_price'].mean()

date_time
1    0.1115
2    0.1115
3    0.1115
Name: e_price, dtype: float64

In [58]:
i = 57
j = i+ (4*(2 -1))
start = time_interval[i]
end = time_interval[j]
df_price = get_data_from_df(
            df=ed2017, 
            start_time=start, 
            end_time=end)
#df_price.groupby([df_price.index.hour])['e_price'].mean()

df_price = df_price.reset_index()
df_price

date_time  e_price  d_price
0 2017-01-01 14:15:00   0.1115    21.08
1 2017-01-01 14:30:00   0.1115    21.08
2 2017-01-01 14:45:00   0.1115    21.08
3 2017-01-01 15:00:00   0.1115    21.08
4 2017-01-01 15:15:00   0.1115    21.08

In [57]:
eprice_ahead_lst = []
for k in range(0,df_price.shape[0],4):
    eprice_ahead_lst.append(df_price.iloc[k]["e_price"])

np.array(eprice_ahead_lst)

array([0.1115, 0.1115, 0.1438])

In [38]:
titi=df_price.groupby([df_price.index.hour])['e_price'].mean()

In [39]:
titi.to_numpy()

AttributeError: 'Series' object has no attribute 'to_numpy'

In [54]:
import numpy as np
#np.array(titi)

In [44]:
time_interval[j+95]

Timestamp('2017-01-02 23:30:00')

In [2]:
main_obs_names = [
            "TOD", "OutTemp", "OutRH", "OutSI",
            "ZoneTempB", "net_power","net_energy",
            "ZoneTotalIlluB", "SOC", "PV"]

In [3]:
eprice_24_ahead =[
            "eprice_t0", "eprice_t1","eprice_t2",
            "eprice_t3", "eprice_t4", "eprice_t5",
            "eprice_t6", "eprice_t7", "eprice_t8",
            "eprice_t9", "eprice_t10", "eprice_t11",
            "eprice_t12", "eprice_t13", "eprice_t14",
            "eprice_t15", "eprice_t16", "eprice_t17",
            "eprice_t18", "eprice_t19", "eprice_t20",
            "eprice_t21", "eprice_t22", "eprice_t23"]

In [13]:
eprice_ehead =4
eprice_x_ahead = eprice_24_ahead[0:eprice_ehead] 
eprice_x_ahead

['eprice_t0', 'eprice_t1', 'eprice_t2', 'eprice_t3']

In [14]:
main_obs_names

['TOD',
 'OutTemp',
 'OutRH',
 'OutSI',
 'ZoneTempB',
 'net_power',
 'net_energy',
 'ZoneTotalIlluB',
 'SOC',
 'PV']

In [15]:
main_obs_names + eprice_x_ahead

['TOD',
 'OutTemp',
 'OutRH',
 'OutSI',
 'ZoneTempB',
 'net_power',
 'net_energy',
 'ZoneTotalIlluB',
 'SOC',
 'PV',
 'eprice_t0',
 'eprice_t1',
 'eprice_t2',
 'eprice_t3']

In [17]:
import numpy as np
np.repeat(3, 4)

array([3, 3, 3, 3])

In [18]:
min_eprice = 10.0

In [21]:
np.repeat(min_eprice, 24)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [26]:
eprice_ehead =4
min_eprice = 100
max_eprice = 1000
main_obs_low = np.array([
            0.0, -20.0, 0.0, 0.0, 
            5.0, -5.0, -1.25, 
            0.0, 0.0, 0.0])
main_obs_high = np.array([
            23.75, 40.0, 100.0, 20000.0,
            35.0, 20.0, 5.0,
            1200.0, 1.0, 5000.0
        ])
eprice_x_ahead_low = np.repeat(min_eprice, eprice_ehead)
eprice_x_ahead_high = np.repeat(max_eprice, eprice_ehead)

obs_space_low = (main_obs_low,eprice_x_ahead_low)
obs_space_low = np.concatenate(obs_space_low)
obs_space_high = (main_obs_high,eprice_x_ahead_high)
obs_space_high = np.concatenate(obs_space_high)

print(obs_space_low)
print(obs_space_high)

[  0.   -20.     0.     0.     5.    -5.    -1.25   0.     0.     0.
 100.   100.   100.   100.  ]
[2.375e+01 4.000e+01 1.000e+02 2.000e+04 3.500e+01 2.000e+01 5.000e+00
 1.200e+03 1.000e+00 5.000e+03 1.000e+03 1.000e+03 1.000e+03 1.000e+03]


In [27]:
len(obs_space_low)

14

In [20]:
start = time_interval[146] 
print(start)

2017-01-02 12:30:00


In [32]:
from datetime import timedelta
import numpy as np

In [34]:
times_ahead = 5 * 60

end = start + timedelta(minutes = times_ahead-15)
print(end)

2017-01-02 17:15:00


In [38]:
df_price = get_data_from_df(
            df=ed2017, 
            start_time=start, 
            end_time=end)
df = df_price.groupby([df_price.index.hour])['e_price'].mean()
df

date_time
12    0.1115
13    0.1115
14    0.1115
15    0.1115
16    0.1438
17    0.1438
Name: e_price, dtype: float64

In [42]:
hours_ahead = 5
np.array(df.iloc[0:hours_ahead,])

array([0.1115, 0.1115, 0.1115, 0.1115, 0.1438])

In [43]:
action_names = ["SaFrB", "SaTempB", "LigB_input", "P_ctrl"]

In [48]:
len(action_names)

4

In [46]:
action_space_low = np.array([0.05, 10.0, 0.0, -3300.0])

In [47]:
action_space_low.shape[0]

4

In [ ]:
action_space_low = np.array([0.05, 10.0, 0.0, -3300.0])